[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_project = "6yTUHanx8FeZBtt8fgC2REX5zFem7pe86ank7b8VaHGm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ytakahashi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
